version: "3.7"

services:
  excalidraw:
    image: excalidraw/excalidraw
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/excalidraw:/app/data
    ports:
      - "9932:80"
