version: "3.7"

services:
  archivebox:
    image: archivebox/archivebox
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/archivebox:/data
    ports:
      - "8766:8000"
    environment:
      ALLOWED_HOSTS: "*"
      USE_COLOR: "True"
